# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.Aluno')),
                ('perfil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'perfil_aluno',
            },
        ),
        migrations.CreateModel(
            name='PerfilCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Curso')),
                ('perfil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'perfil_curso',
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_aluno',
            field=models.ManyToManyField(through='perfil.PerfilAluno', to='aluno.Aluno'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_curso',
            field=models.ManyToManyField(through='perfil.PerfilCurso', to='curso.Curso'),
        ),
    ]
