# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilaluno',
            old_name='aluno_id',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='perfilaluno',
            old_name='perfil_id',
            new_name='perfil',
        ),
        migrations.RenameField(
            model_name='perfilcurso',
            old_name='curso_id',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='perfilcurso',
            old_name='perfil_id',
            new_name='perfil',
        ),
    ]
