# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20170619_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='matriculas',
        ),
    ]
