# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='perfil_curso',
            field=models.ManyToManyField(through='perfil.PerfilCurso', to='perfil.Perfil'),
        ),
    ]
