# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20170620_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='moodle_id',
        ),
    ]
