# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdlgradegrades',
            name='itemid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='mdlgradegrades',
            name='userid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='mdlgradeitems',
            name='courseid',
            field=models.BigIntegerField(),
        ),
    ]
